name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: flake8 .

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=term-missing:skip-covered --cov-fail-under=80

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t myapp:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push myapp:${{ github.sha }}

    - name: Output Docker run command
      run: "echo 'Run the following command to pull and run the Docker image locally: docker run -p 8000:8000 myapp:${{ github.sha }}'"